# Generated by Django 3.2.6 on 2021-08-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpub_data',
            new_name='bpub_date',
        ),
    ]
