# Generated by Django 3.2.6 on 2021-08-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_bookinfo_bcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=20)),
                ('aParent', models.ForeignKey(blank=True, default='没有省', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='booktest.areainfo')),
            ],
        ),
    ]
