# Generated by Django 3.1.4 on 2021-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_pictest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictest',
            name='pic_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='atitle',
            field=models.CharField(max_length=20, verbose_name='地区'),
        ),
    ]
