# Generated by Django 3.1.4 on 2021-08-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0009_auto_20210812_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictest',
            old_name='pic',
            new_name='pic_path',
        ),
    ]
